- name: Automatic Release With Assets
  # You may pin to the exact commit or the version.
  # uses: ianlapham/release-and-build@030426b9672f91f97f134a6e5463fbd2fe53d49f
  uses: ianlapham/release-and-build@v1
  with:
    # GitHub secret token
    repo_token: 
    # Git tag (for automatic releases)
    automatic_release_tag: # optional
    # Should this release be marked as a draft?
    draft: # optional
    # Should this release be marked as a pre-release?
    prerelease: # optional, default is true
    # Release title (for automatic releases)
    title: # optional
    # Assets to upload to the release
    files: 
    *.rb
